name: Update Portfolio with New PRs

on:
  schedule:
    - cron: '0 2 * * *' 
  workflow_dispatch:

jobs:
  update-portfolio-with-new-merged-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Fetch new merged PRs and update portfolio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: bun .github/scripts/fetch_new_merged_prs.ts

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update portfolio with new merged PRs [skip ci]" ||  echo "No changes"
          git push origin HEAD:centered-content
